### ISSUE TITLE
Future Roadmap

### ISSUE THREAD

**Issue by mgratch** [nopressureselling/NoPresureSelling.com#1]
- [ ] Migrate any other NPS sites to WPEngine and close unnecessary hosting accounts.
- [ ] Set blog hero image to pop up in safari reader mode
- [ ] Add subhead to each blog on the blog archive page
- [x] Add "Next/Previous" Articles to the bottom of each single blog page
- [ ] Add a blog highlight option and style
- [ ] Add tagging to blogs
- [ ] Add Commenting
- [ ] Replace Contact Form 7 with Gravity Forms.
- [ ] ROI Web App
- [ ] Removing Code Kit 
- [ ] Remove LESS
- [ ] Remove Pods
- [ ] Remove Ubermenu
- [ ] Remove ACF
- [ ] Remove Twig templating
